### ISSUE TITLE
question about the language semantic

### ISSUE THREAD

**Issue by c8ef** [pku-minic/first-step#1]
I have come across a program that seems to be causing a segment fault. The code is as follows:
```
fact(n) {
  if n <= 1 {
    return 1
  }
  return n * fact(n - 1)
}

main() {
  print(fact(7))
  return 0
}
```
Upon further investigation, it seems that the BlockAST is calling `Eval` on all of its sub-nodes, irrespective of whether there is a `return` statement earlier in the code. I am curious to know if this behavior is intentional or if it might be considered a bug.

**Comment by MaxXSoft** [comment]
> I am curious to know if this behavior is intentional or if it might be considered a bug.

It is a bug.

The right way to evaluate code blocks and returns is:

* Do not use environment to pass return values.
* Change the return type of all `Eval` functions to a variant type, that can represents a value, void, and another state that indicates function return (with the return value).
* Handle the `return` state in all `Eval` implementations:
  * When evaluating functions, evaluate the function body, it's expected to return a return state, unwrap the return value and return it as a value.
  * When evaluating other ASTs, if a return state is encountered, just stop executing, and "throw" (actually return) the state to the caller.

This repository is deprecated (but has not been marked as "archived" yet), so I'm not going to fix this. And unfortunately there are no other repositories about interpreters in this organization. If you want to know how to write an interpreter, you can check out:

* [examples of `laps` library (Rust)](https://github.com/MaxXSoft/laps/tree/master/examples).
* [examples of `koopa` library (Rust)](https://github.com/pku-minic/koopa/tree/master/examples/interpreter).

**Comment by c8ef** [comment]
Thank you for your prompt and comprehensive response! Your insights are immensely valuable and greatly appreciated.
I plan to study the "Mimic" project, which has a very clear architecture and highly optimized compilation backend.
